### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm, the CI error is a new one @vladikoff

**Comment by vladikoff** [comment]
yeah I know, I'm investigating the issue atm

**Comment by XhmikosR** [comment]
I still believe you shouldn't do it like that. Better have clean patches.

**Comment by vladikoff** [comment]
Sure!

**Comment by XhmikosR** [comment]
I mean, if I go to the git log I will see `v1.0.0` but that doesn't reflect the changes you made :)

**Comment by XhmikosR** [comment]
Also, @shama, I'm still waiting for the guidelines and the internal new version in order to backport the changes to the contrib plugins.

**Comment by vladikoff** [comment]
@XhmikosR link?

**Comment by XhmikosR** [comment]
@vladikoff: https://github.com/gruntjs/grunt-contrib-nodeunit/pull/44/commits

This PR should be 2 separate patches IMO. One with the fixes and one with the version bump.

**Comment by vladikoff** [comment]
@XhmikosR I meant do you have a link to discuss the guidelines for : 

> Also, @shama, I'm still waiting for the guidelines and the internal new version in order to backport the changes to the contrib plugins.

**Comment by XhmikosR** [comment]
Oh, sorry, it was in a previous PR we had. We need to gather all this in an issue or something so that we are all in sync.

**Pull request closed without merging**
